### ISSUE TITLE
Wut are backing variables? 

### ISSUE THREAD

**Issue by kjsb25** [MichaelRallo/OOComparison#1]

**Comment by MichaelRallo** [comment]
I believe it's a C# only thing.
Read up here: http://stackoverflow.com/questions/12736237/using-a-backing-variable-for-getters-and-setters.

I think it's just a way to manage setting/getting vars easier and ensuring correct values go where needed.

**Comment by kjsb25** [comment]
lol, didnt expect you to actually respond. Was just making a note to ask ya tomorrow. 

Yea, that's what I'm finding too. Just seemed odd for him to ask if it was central to one language, so wanted to get your thoughts. I'll put in as no for both then.
